import 'dart:convert';
import 'package:http/http.dart' as http;

/// A single caption/transcript entry.
class TranscriptEntry {
  final double start;
  final double duration;
  final String text;

  const TranscriptEntry({
    required this.start,
    required this.duration,
    required this.text,
  });

  double get end => start + duration;

  @override
  String toString() => '${start.toStringAsFixed(2)}s -> $text';
}

/// Pure-HTTP YouTube transcript extractor.
/// Uses POST /youtubei/v1/get_transcript with keys extracted live from the page.
class YouTubeTranscriptService {
  static const String _userAgent =
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
      'AppleWebKit/537.36 (KHTML, like Gecko) '
      'Chrome/124.0.0.0 Safari/537.36';

  // ── public API ────────────────────────────────────────────────────────────

  Future<List<TranscriptEntry>> fetch(
    String videoIdOrUrl, {
    List<String> preferredLanguages = const ['en'],
  }) async {
    final videoId = _parseVideoId(videoIdOrUrl);
    print('  Video ID: $videoId');

    // One page fetch gives us everything: api key, client version,
    // visitor data, and the caption track list.
    final pageData = await _fetchPageData(videoId);

    final apiKey        = pageData['apiKey']        as String;
    final clientVersion = pageData['clientVersion'] as String;
    final visitorData   = pageData['visitorData']   as String;
    final tracks        = pageData['tracks']        as List<Map<String, dynamic>>;

    print('  API key: ${apiKey.isNotEmpty ? apiKey.substring(0, 12) + "..." : "❌ missing"}');
    print('  Client version: $clientVersion');
    print('  Visitor data: ${visitorData.isNotEmpty ? "✅" : "⚠️  missing"}');
    print('  Tracks: ${tracks.map((t) => t['languageCode']).toList()}');

    if (tracks.isEmpty) {
      throw TranscriptException(videoId, 'No caption tracks found.');
    }

    final track = _selectTrack(tracks, preferredLanguages);
    print('  Selected: ${track['languageName']} '
        '(${track['languageCode']}, asr=${track['isAutoGenerated']})');

    return _fetchViaInnerApi(
      videoId: videoId,
      languageCode: track['languageCode'] as String,
      apiKey: apiKey,
      clientVersion: clientVersion,
      visitorData: visitorData,
    );
  }

  Future<String> fetchAsString(
    String videoIdOrUrl, {
    List<String> preferredLanguages = const ['en'],
  }) async {
    final entries =
        await fetch(videoIdOrUrl, preferredLanguages: preferredLanguages);
    return entries
        .map((e) => e.text)
        .join(' ')
        .replaceAll(RegExp(r'\s+'), ' ')
        .trim();
  }

  // ── step 1: fetch watch page and extract everything we need ───────────────

  Future<Map<String, dynamic>> _fetchPageData(String videoId) async {
    final response = await http.get(
      Uri.parse('https://www.youtube.com/watch?v=$videoId'),
      headers: {
        'User-Agent': _userAgent,
        'Accept-Language': 'en-US,en;q=0.9',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Cookie': 'CONSENT=YES+1; SOCS=CAESEwgDEgk0OTI3NTU4MTUaAmVuIAEaBgiA_LyiBg',
      },
    );

    if (response.statusCode != 200) {
      throw TranscriptException(
          videoId, 'Watch page HTTP ${response.statusCode}');
    }

    final html = response.body;

    // ── extract INNERTUBE_API_KEY ──────────────────────────────────────────
    // Present as: "INNERTUBE_API_KEY":"AIzaSy..."
    // or:          INNERTUBE_API_KEY":"AIzaSy..."
    String apiKey = '';
    final apiKeyMatch = RegExp(r'"INNERTUBE_API_KEY"\s*:\s*"([^"]+)"')
        .firstMatch(html);
    if (apiKeyMatch != null) {
      apiKey = apiKeyMatch.group(1)!;
    }

    // ── extract clientVersion ──────────────────────────────────────────────
    // Present as: "clientVersion":"2.20240101.00.00"
    // or inside INNERTUBE_CONTEXT_CLIENT_VERSION
    String clientVersion = '2.20240101.00.00'; // sensible fallback
    final cvMatch = RegExp(
            r'"(?:INNERTUBE_CONTEXT_CLIENT_VERSION|clientVersion)"\s*:\s*"([^"]+)"')
        .firstMatch(html);
    if (cvMatch != null) {
      clientVersion = cvMatch.group(1)!;
    }

    // ── extract visitorData ────────────────────────────────────────────────
    String visitorData = '';
    final vdMatch =
        RegExp(r'"visitorData"\s*:\s*"([^"]+)"').firstMatch(html);
    if (vdMatch != null) {
      visitorData = vdMatch.group(1)!;
    }

    // ── extract caption tracks from ytInitialPlayerResponse ───────────────
    List<Map<String, dynamic>> tracks = [];
    if (html.contains('ytInitialPlayerResponse')) {
      try {
        final playerResponse = _extractJsonObject(html, 'ytInitialPlayerResponse');
        tracks = _parseCaptionTracks(playerResponse);
      } catch (e) {
        print('  ⚠️  Could not parse caption tracks: $e');
      }
    }

    return {
      'apiKey': apiKey,
      'clientVersion': clientVersion,
      'visitorData': visitorData,
      'tracks': tracks,
    };
  }

  // ── step 2: POST to /youtubei/v1/get_transcript ───────────────────────────

  Future<List<TranscriptEntry>> _fetchViaInnerApi({
    required String videoId,
    required String languageCode,
    required String apiKey,
    required String clientVersion,
    required String visitorData,
  }) async {
    if (apiKey.isEmpty) {
      throw TranscriptException(videoId,
          'Could not extract INNERTUBE_API_KEY from watch page.');
    }

    final params = _buildProtoParams(videoId, languageCode);
    print('  params: $params');

    final url = Uri.parse(
        'https://www.youtube.com/youtubei/v1/get_transcript?key=$apiKey');

    final requestBody = jsonEncode({
      'context': {
        'client': {
          'clientName': 'WEB',
          'clientVersion': clientVersion,
          'hl': 'en',
          'gl': 'US',
          'userAgent': '$_userAgent,gzip(gfe)',
          if (visitorData.isNotEmpty) 'visitorData': visitorData,
        },
      },
      'params': params,
    });

    final headers = {
      'User-Agent': _userAgent,
      'Content-Type': 'application/json',
      'Accept': '*/*',
      'Accept-Language': 'en-US,en;q=0.9',
      'Origin': 'https://www.youtube.com',
      'Referer': 'https://www.youtube.com/watch?v=$videoId',
      'Cookie': 'CONSENT=YES+1; SOCS=CAESEwgDEgk0OTI3NTU4MTUaAmVuIAEaBgiA_LyiBg',
      'X-Youtube-Client-Name': '1',
      'X-Youtube-Client-Version': clientVersion,
      if (visitorData.isNotEmpty) 'X-Goog-Visitor-Id': visitorData,
    };

    final response = await http.post(url, headers: headers, body: requestBody);

    print('  get_transcript status: ${response.statusCode}');
    print('  get_transcript bytes: ${response.bodyBytes.length}');
    if (response.statusCode != 200) {
      print('  Error body: ${response.body}');
      throw TranscriptException(videoId,
          'get_transcript failed (HTTP ${response.statusCode}).');
    }

    final json = jsonDecode(response.body) as Map<String, dynamic>;
    return _parseInnerApiResponse(json);
  }

  // ── protobuf encoder ──────────────────────────────────────────────────────
  //
  // Encodes: { 1: videoId, 2: { 1: languageCode } }
  //
  //   field 1, wire=2 (LEN)  tag=0x0a
  //   field 2, wire=2 (LEN)  tag=0x12
  //   field 1, wire=2 (LEN)  tag=0x0a  (inside nested message)

  String _buildProtoParams(String videoId, String languageCode) {
    final buf = <int>[];

    void writeString(int fieldNumber, String value) {
      final bytes = utf8.encode(value);
      buf.add((fieldNumber << 3) | 2); // wire type 2 = LEN
      _writeVarint(buf, bytes.length);
      buf.addAll(bytes);
    }

    void writeMessage(int fieldNumber, void Function() inner) {
      final inner_buf = <int>[];
      // temporarily capture writes into inner_buf
      final saved = List<int>.from(buf);
      buf.clear();
      inner();
      final innerBytes = List<int>.from(buf);
      buf.clear();
      buf.addAll(saved);
      buf.add((fieldNumber << 3) | 2);
      _writeVarint(buf, innerBytes.length);
      buf.addAll(innerBytes);
    }

    // Field 1: videoId
    writeString(1, videoId);

    // Field 2: nested { field 1: languageCode }
    writeMessage(2, () => writeString(1, languageCode));

    return base64.encode(buf);
  }

  void _writeVarint(List<int> buf, int value) {
    while (value > 0x7F) {
      buf.add((value & 0x7F) | 0x80);
      value >>= 7;
    }
    buf.add(value);
  }

  // ── parse get_transcript response ─────────────────────────────────────────

  List<TranscriptEntry> _parseInnerApiResponse(Map<String, dynamic> json) {
    try {
      final actions = json['actions'] as List<dynamic>?;
      if (actions == null || actions.isEmpty) {
        print('  Response keys: ${json.keys.toList()}');
        throw TranscriptException(null, 'No actions in response.');
      }

      Map<String, dynamic>? segmentList;
      for (final action in actions) {
        final found = _dig(action, [
          'updateEngagementPanelAction', 'content',
          'transcriptRenderer', 'content',
          'transcriptSearchPanelRenderer', 'body',
          'transcriptSegmentListRenderer',
        ]);
        if (found != null) {
          segmentList = found as Map<String, dynamic>;
          break;
        }
      }

      if (segmentList == null) {
        print('  Action keys: ${(actions[0] as Map).keys.toList()}');
        throw TranscriptException(null, 'transcriptSegmentListRenderer not found.');
      }

      final segments = segmentList['initialSegments'] as List<dynamic>? ?? [];
      final entries = <TranscriptEntry>[];

      for (final seg in segments) {
        final renderer = (seg as Map<String, dynamic>)['transcriptSegmentRenderer']
            as Map<String, dynamic>?;
        if (renderer == null) continue;

        final startMs = double.tryParse(renderer['startMs']?.toString() ?? '0') ?? 0.0;
        final endMs   = double.tryParse(renderer['endMs']?.toString()   ?? '0') ?? 0.0;

        final runs = _dig(renderer, ['snippet', 'runs']) as List<dynamic>? ?? [];
        final text = runs
            .map((r) => (r as Map)['text'] as String? ?? '')
            .join('')
            .replaceAll('\n', ' ')
            .trim();

        if (text.isNotEmpty) {
          entries.add(TranscriptEntry(
            start:    startMs / 1000.0,
            duration: (endMs - startMs) / 1000.0,
            text:     text,
          ));
        }
      }

      print('  ✅ ${entries.length} entries parsed.');
      return entries;
    } catch (e) {
      if (e is TranscriptException) rethrow;
      throw TranscriptException(null, 'Parse error: $e');
    }
  }

  // ── helpers ───────────────────────────────────────────────────────────────

  Map<String, dynamic> _extractJsonObject(String html, String varName) {
    final idx = html.indexOf(varName);
    if (idx == -1) throw Exception('$varName not found');
    final braceStart = html.indexOf('{', idx);
    if (braceStart == -1) throw Exception('No { after $varName');
    int depth = 0, i = braceStart;
    while (i < html.length) {
      if (html[i] == '{') depth++;
      if (html[i] == '}') { depth--; if (depth == 0) break; }
      i++;
    }
    return jsonDecode(html.substring(braceStart, i + 1)) as Map<String, dynamic>;
  }

  dynamic _dig(dynamic obj, List<dynamic> path) {
    dynamic cur = obj;
    for (final key in path) {
      if (cur == null) return null;
      if (cur is Map)  cur = cur[key];
      else if (cur is List && key is int) cur = cur[key];
      else return null;
    }
    return cur;
  }

  List<Map<String, dynamic>> _parseCaptionTracks(
      Map<String, dynamic> playerResponse) {
    try {
      final renderer = _dig(playerResponse, [
        'captions', 'playerCaptionsTracklistRenderer'
      ]) as Map<String, dynamic>?;
      final rawTracks = renderer?['captionTracks'] as List<dynamic>?;
      if (rawTracks == null) return [];
      return rawTracks.map((t) {
        final track = t as Map<String, dynamic>;
        final langCode = (track['languageCode'] as String? ?? '').toLowerCase();
        final langName = (track['name']?['simpleText'] as String?) ??
            (track['name']?['runs']?[0]?['text'] as String?) ?? langCode;
        return <String, dynamic>{
          'languageCode': langCode,
          'languageName': langName,
          'isAutoGenerated': track['kind'] == 'asr',
        };
      }).toList();
    } catch (_) { return []; }
  }

  Map<String, dynamic> _selectTrack(
    List<Map<String, dynamic>> tracks,
    List<String> preferredLanguages,
  ) {
    final Map<String, dynamic> notFound = {};
    for (final lang in preferredLanguages) {
      final m = tracks.firstWhere(
        (t) => (t['languageCode'] as String).startsWith(lang.toLowerCase()) &&
            !(t['isAutoGenerated'] as bool),
        orElse: () => notFound,
      );
      if (m.isNotEmpty) return m;
    }
    for (final lang in preferredLanguages) {
      final m = tracks.firstWhere(
        (t) => (t['languageCode'] as String).startsWith(lang.toLowerCase()),
        orElse: () => notFound,
      );
      if (m.isNotEmpty) return m;
    }
    return tracks.first;
  }

  String _parseVideoId(String input) {
    if (RegExp(r'^[a-zA-Z0-9_\-]{11}$').hasMatch(input)) return input;
    final uri = Uri.tryParse(input);
    if (uri == null) return input;
    final v = uri.queryParameters['v'];
    if (v != null && v.isNotEmpty) return v;
    if (uri.host == 'youtu.be' && uri.pathSegments.isNotEmpty) {
      return uri.pathSegments.first;
    }
    if (uri.pathSegments.length >= 2 &&
        (uri.pathSegments[0] == 'embed' || uri.pathSegments[0] == 'shorts')) {
      return uri.pathSegments[1];
    }
    return input;
  }
}

// ── exception ─────────────────────────────────────────────────────────────────

class TranscriptException implements Exception {
  final String? videoId;
  final String message;
  const TranscriptException(this.videoId, this.message);

  @override
  String toString() => videoId != null
      ? 'TranscriptException [$videoId]: $message'
      : 'TranscriptException: $message';
}